version: '3.8'

services:
  db2:
    image: icr.io/db2_community/db2
    platform: linux/amd64
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2fdw
      DBNAME: testdb
  dev:
    image: builder
    platform: linux/amd64
    volumes:
      - ./:/host
    command:
      - /bin/bash
      - -c
      - while sleep 1; do echo -n .; done
  builder:
    image: builder
    build:
      context: .
      args:
        - PGVERSION=${PGVERSION}
    platform: linux/amd64
    volumes:
      - ./:/host
    command: /host/scripts/build_rpm.sh
  rpmsigner:
    image: builder
    command:
      - /host/scripts/sign_rpms.sh
    volumes:
      - ./:/host
    environment:
      - GPG_PASSPHRASE
      - GPG_KEY_B64
