version: '3.8'

services:
  builder:
    build:
      context: .
      args:
        - PGVERSION=${PGVERSION}
    platform: linux/amd64
    volumes:
      - ./:/host
    command: /host/scripts/build_rpm.sh
