version: '3.8'

services:
  db2:
    image: icr.io/db2_community/db2
    platform: linux/amd64
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=testpwd
      - DBNAME=test
      - DB2_HOME=/opt/ibm/db2/V12.1
    ports:
      - '50000:50000'
    volumes:
      - ./:/host
    command: |
      dnf update -y
      dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      dnf -qy module disable postgresql
      dnf install -y postgresql17-server postgresql17-devel git redhat-rpm-config
      mkdir -p ~/git/ && cd ~/git
      git clone https://github.com/wolfgangbrandl/db2_fdw.git && cd db2_fdw
      export PATH=$PATH:/usr/pgsql-17/bin
      make && make install
